name: Unzip Pawn Compiler

on:
  push:
    paths:
      - 'SAMP-AML-Mod.zip'
  workflow_dispatch:

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # نستخدم التوكن الجديد الذي أنشأته هنا
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Unzip SAMP-AML-Mod.zip
        run: |
          unzip -o SAMP-AML-Mod.zip -d .
          # اختياري: إذا كنت لا تريد تحديث ملفات الـ workflow من داخل الـ zip لمنع الأخطاء مستقبلاً
          # rm -rf .github/workflows/build.yml 

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-unzip SAMP-AML-Mod.zip content"
          file_pattern: '*'
