name: Unzip Pawn Compiler

on:
  push:
    paths:
      - 'SAMP-AML-Mod.zip'
  workflow_dispatch:

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # لصلاحية التعديل على الملفات العادية
      workflows: write  # هذه هي الصلاحية المطلوبة لتعديل ملفات الـ workflow داخل الـ zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip SAMP-AML-Mod.zip
        run: |
          unzip -o SAMP-AML-Mod.zip -d .

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-unzip SAMP-AML-Mod.zip content"
          file_pattern: '*'
